[package]
org = "xlibb"
name = "graphql_federation_gateway"
version = "@toml.version@"
authors = ["Ballerina"]
export=["graphql_federation_gateway"]
keywords = ["graphql", "federation", "gateway"]
repository = "https://github.com/xlibb/graphql-federation-gateway"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.xlibb.gateway"
artifactId = "gateway-native"
version = "@toml.version@"
path = "../native/build/libs/gateway-native-@project.version@.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java"
version = "@graphql.java.version@"
path="./lib/graphql-java-@graphql.java.version@.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java-extended-scalars"
version = "@graphql.java.extended.scalars.version@"
path="./lib/graphql-java-extended-scalars-@graphql.java.extended.scalars.version@.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-io"
version = "@commons.io.version@"
path="./lib/commons-io-@commons.io.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "@ballerina.lang.version@"
path="./lib/formatter-core-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-lang"
version = "@ballerina.lang.version@"
path="./lib/ballerina-lang-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "@ballerina.lang.version@"
path="./lib/ballerina-parser-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-runtime"
version = "@ballerina.lang.version@"
path="./lib/ballerina-runtime-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-tools-api"
version = "@ballerina.lang.version@"
path="./lib/ballerina-tools-api-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "com.github.zafarkhaja"
artifactId = "java-semver"
version = "0.9.0"
path="./lib/java-semver-0.9.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "central-client"
version = "@ballerina.lang.version@"
path="./lib/central-client-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.21"
path="./lib/commons-compress-1.21.jar"

[[platform.java11.dependency]]
path="./lib/okhttp-3.14.0.jar"

[[platform.java11.dependency]]
path="./lib/okio-2.2.2.jar"

[[platform.java11.dependency]]
path="./lib/kotlin-stdlib-1.2.60.jar"

[[platform.java11.dependency]]
path="./lib/asm-7.2.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-@ballerina.lang.version@.jar"
