[package]
org = "xlibb"
name = "graphql_federation_gateway"
version = "@toml.version@"
authors = ["Ballerina"]
export=["graphql_federation_gateway"]
keywords = ["graphql", "federation", "gateway"]
repository = "https://github.com/xlibb/graphql-federation-gateway"
license = ["Apache-2.0"]
distribution = "@ballerina.lang.version@"

[[platform.java11.dependency]]
groupId = "io.xlibb.gateway"
artifactId = "gateway-native"
version = "@toml.version@"
path = "../native/build/libs/gateway-native-@project.version@.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java"
version = "@graphql.java.version@"
path="./lib/graphql-java-@graphql.java.version@.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java-extended-scalars"
version = "@graphql.java.extended.scalars.version@"
path="./lib/graphql-java-extended-scalars-@graphql.java.extended.scalars.version@.jar"

[[platform.java11.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "@commons.io.version@"
path="./lib/commons-io-@commons.io.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "@ballerina.lang.version@"
path="./lib/formatter-core-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-lang"
version = "@ballerina.lang.version@"
path="./lib/ballerina-lang-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "@ballerina.lang.version@"
path="./lib/ballerina-parser-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-runtime"
version = "@ballerina.lang.version@"
path="./lib/ballerina-runtime-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-tools-api"
version = "@ballerina.lang.version@"
path="./lib/ballerina-tools-api-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "central-client"
version = "@ballerina.lang.version@"
path="./lib/central-client-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "maven-resolver"
version = "@ballerina.lang.version@"
path="./lib/maven-resolver-@ballerina.lang.version@.jar"

[[platform.java11.dependency]]
groupId = "com.github.zafarkhaja"
artifactId = "java-semver"
version = "@java.semver.version@"
path="./lib/java-semver-@java.semver.version@.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "@commons.compress.version@"
path="./lib/commons-compress-@commons.compress.version@.jar"

[[platform.java11.dependency]]
groupId = "com.squareup.okhttp3"
artifactId = "okhttp"
version = "@okhttp.version@"
path="./lib/okhttp-@okhttp.version@.jar"

[[platform.java11.dependency]]
groupId = "com.squareup.okio"
artifactId = "okio"
version = "@okio.version@"
path="./lib/okio-@okio.version@.jar"

[[platform.java11.dependency]]
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib"
version = "@kotlin.version@"
path="./lib/kotlin-stdlib-@kotlin.version@.jar"

[[platform.java11.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm"
version = "@asm.version@"
path="./lib/asm-@asm.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"
path="./lib/netty-common-@netty.version@.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"
path="./lib/netty-buffer-@netty.version@.jar"
