[package]
org = "xlibb"
name = "graphql_federation_gateway"
version = "0.1.0"
authors = ["Ballerina"]
export=["graphql_federation_gateway"]
keywords = ["graphql", "federation", "gateway"]
repository = "https://github.com/xlibb/graphql-federation-gateway"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.xlibb.gateway"
artifactId = "gateway-native"
version = "0.1.0"
path = "../native/build/libs/gateway-native-0.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java"
version = "20.0"
path="./lib/graphql-java-20.0.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java-extended-scalars"
version = "20.0"
path="./lib/graphql-java-extended-scalars-20.0.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-io"
version = "2.11.0"
path="./lib/commons-io-2.11.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2201.6.0"
path="./lib/formatter-core-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-lang"
version = "2201.6.0"
path="./lib/ballerina-lang-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2201.6.0"
path="./lib/ballerina-parser-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "com.github.zafarkhaja"
artifactId = "java-semver"
version = "0.9.0"
path="./lib/java-semver-0.9.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "central-client"
version = "2201.6.0"
path="./lib/central-client-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.21"
path="./lib/commons-compress-1.21.jar"

[[platform.java11.dependency]]
path="./lib/okhttp-3.14.0.jar"

[[platform.java11.dependency]]
path="./lib/okio-2.2.2.jar"

[[platform.java11.dependency]]
path="./lib/kotlin-stdlib-1.2.60.jar"

[[platform.java11.dependency]]
path="./lib/asm-7.2.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-2201.6.0.jar"