[package]
org = "xlibb"
name = "graphql_federation_gateway"
version = "0.1.0"
authors = ["Ballerina"]
export=["graphql_federation_gateway"]
keywords = ["graphql", "federation", "gateway"]
repository = "https://github.com/xlibb/graphql-federation-gateway"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.xlibb.gateway"
artifactId = "gateway-native"
version = "0.1.0"
path = "../native/build/libs/gateway-native-0.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java"
version = "20.0"
path="./lib/graphql-java-20.0.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java-extended-scalars"
version = "20.0"
path="./lib/graphql-java-extended-scalars-20.0.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-io"
version = "2.11.0"
path="./lib/commons-io-2.11.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2201.6.0"
path="./lib/formatter-core-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-lang"
version = "2201.6.0"
path="./lib/ballerina-lang-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2201.6.0"
path="./lib/ballerina-parser-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-runtime"
version = "2201.6.0"
path="./lib/ballerina-runtime-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-tools-api"
version = "2201.6.0"
path="./lib/ballerina-tools-api-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "com.github.zafarkhaja"
artifactId = "java-semver"
version = "0.9.0"
path="./lib/java-semver-0.9.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "central-client"
version = "2201.6.0"
path="./lib/central-client-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.21"
path="./lib/commons-compress-1.21.jar"

[[platform.java11.dependency]]
path="./lib/okhttp-3.14.0.jar"

[[platform.java11.dependency]]
path="./lib/annotations-13.0.jar"

[[platform.java11.dependency]]
path="./lib/apache-mime4j-core-0.8.6.jar"

[[platform.java11.dependency]]
path="./lib/asm-7.2.jar"

[[platform.java11.dependency]]
path="./lib/axiom-api-1.4.0.jar"

[[platform.java11.dependency]]
path="./lib/axiom-impl-1.4.0.jar"

[[platform.java11.dependency]]
path="./lib/commons-codec-1.11.jar"

[[platform.java11.dependency]]
path="./lib/commons-lang3-3.12.0.jar"

[[platform.java11.dependency]]
path="./lib/commons-logging-1.2.jar"

[[platform.java11.dependency]]
path="./lib/commons-text-1.10.0.jar"

[[platform.java11.dependency]]
path="./lib/gson-2.8.9.jar"

[[platform.java11.dependency]]
path="./lib/httpclient-4.5.13.jar"

[[platform.java11.dependency]]
path="./lib/httpcore-4.4.14.jar"

[[platform.java11.dependency]]
path="./lib/identifier-util-2201.6.0.jar"

[[platform.java11.dependency]]
path="./lib/jakarta.activation-api-1.2.2.jar"

[[platform.java11.dependency]]
path="./lib/jansi-1.18.jar"

[[platform.java11.dependency]]
path="./lib/java-dataloader-3.2.0.jar"

[[platform.java11.dependency]]
path="./lib/javax.annotation-api-1.3.2.jar"

[[platform.java11.dependency]]
path="./lib/javax.inject-1.jar"

[[platform.java11.dependency]]
path="./lib/javax.transaction-api-1.3.jar"

[[platform.java11.dependency]]
path="./lib/jline-3.11.0.jar"

[[platform.java11.dependency]]
path="./lib/jsr305-3.0.2.jar"

[[platform.java11.dependency]]
path="./lib/toml-parser-2201.6.0.jar"

[[platform.java11.dependency]]
path="./lib/okio-2.2.2.jar"

[[platform.java11.dependency]]
path="./lib/kotlin-stdlib-1.2.60.jar"

[[platform.java11.dependency]]
path="./lib/kotlin-stdlib-common-1.2.60.jar"

[[platform.java11.dependency]]
path="./lib/maven-artifact-3.6.3.jar"

[[platform.java11.dependency]]
path="./lib/maven-builder-support-3.6.3.jar"

[[platform.java11.dependency]]
path="./lib/maven-model-3.6.3.jar"

[[platform.java11.dependency]]
path="./lib/maven-model-builder-3.6.3.jar"

[[platform.java11.dependency]]
path="./lib/maven-repository-metadata-3.6.3.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-2201.6.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-api-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-connector-basic-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-impl-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-named-locks-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-provider-3.6.3.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-spi-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-transport-file-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-transport-http-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/maven-resolver-util-1.7.0.jar"

[[platform.java11.dependency]]
path="./lib/netty-buffer-4.1.77.Final.jar"

[[platform.java11.dependency]]
path="./lib/netty-common-4.1.77.Final.jar"

[[platform.java11.dependency]]
path="./lib/opentelemetry-api-1.0.0.jar"

[[platform.java11.dependency]]
path="./lib/opentelemetry-context-1.0.0.jar"

[[platform.java11.dependency]]
path="./lib/org.eclipse.sisu.inject-0.3.4.jar"

[[platform.java11.dependency]]
path="./lib/plexus-interpolation-1.25.jar"

[[platform.java11.dependency]]
path="./lib/plexus-utils-3.2.1.jar"

[[platform.java11.dependency]]
path="./lib/progressbar-0.7.4.jar"

[[platform.java11.dependency]]
path="./lib/reactive-streams-1.0.3.jar"

[[platform.java11.dependency]]
path="./lib/slf4j-api-1.7.35.jar"

[[platform.java11.dependency]]
path="./lib/stax2-api-4.2.1.jar"

[[platform.java11.dependency]]
path="./lib/toml4j-0.7.2.jar"

[[platform.java11.dependency]]
path="./lib/toml-parser-2201.6.0.jar"

[[platform.java11.dependency]]
path="./lib/transactions-5.0.8.jar"

[[platform.java11.dependency]]
path="./lib/transactions-api-5.0.8.jar"

[[platform.java11.dependency]]
path="./lib/transactions-jta-5.0.8.jar"

[[platform.java11.dependency]]
path="./lib/woodstox-core-6.2.8.jar"
